apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:4lcAqfJ5tKyRYs9/WhWpcdsv+OFhIGvh,iv:KzfffHnlIh/FpS17QtJU+D9ssl3poNsUXLjJ+EZxvrI=,tag:bFZyF18civMkfp1ed540gw==,type:str]
    client_secret: ENC[AES256_GCM,data:uE/SBVkszsrcP3Td+LZFKCbRrvhD1xzxEFLyzQZyHz45Z/V7+8o9Rwr1jabEwVc8/fNslFYen5KmRYWhjIW1UKSyua/r36zQ6S17wA0lV/tO8eBFRMsM0Q==,iv:0yYt3xrnCO6rZKPud7zDxAiavClEDYNz3XtxEh8pPS4=,tag:H5G8kwMoXFhvR7gk93IkPw==,type:str]
kind: Secret
metadata:
    name: operator-oauth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySFlPdDA5ZzJwU0JyeHpW
            cC8vUWk1Q2dQUStrN1AzWSt0R2IvV3VTQVV3CmZoYjhWb1hELy9IOWhJUnU1WExw
            WWdzSGgrakJqdnlIczR2WW1tdDR1MEkKLS0tIEtPenZzVzVMSUYySXUvRFArRzhS
            dU1Ec1FFbkZjYVF1cDhGcittNU1UWmMKGx+tXRh4P7TWUFiAbA7THm1td4FgxfC/
            yTGd/igSVFj3uPmrOgGOkVjNKHHP+XCnZ7u4oq7jyipcOhdXkTUSxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8k7asxtckf8nmxnf8lvlp4dzcgsnaamdj6q9pl9e2w3mhhz69ts3pyhuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T15:07:48Z"
    mac: ENC[AES256_GCM,data:vgs0UKgeHPe26g5yjub9xlN/dvgCXE/MxKZnuDu0030JBKSzhG9NOP9DC53+rWCsp7b/OnFZOt4B0lMewQNJseBiDEhBslzn5OqMIgL4sNPFhXh/YSJHbwSH2Xz/aDmhDOYHYLXHmDJWpDefizVua/551RbC9J3twH8VjdM+/HI=,iv:pCPT5pEMHr1GAMJe+3+VdTsJdnyh3BZiIvYYbH9HRV4=,tag:J/Fc25tieE24J0RrCIEwUw==,type:str]
    version: 3.13.3
