apiVersion: v1
data:
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:JgIKh9MMFefIbQz9FDaWUAiYDq/gSdoUeZbNIOxzKmz3aco3evn61aVnrnLjgwQ6zz/OgA6eBS8ULPczF0t2ml+6DyXrq/Ss8JNWoNRB7ED4DNy2OfbfEQ==,iv:P2K7nAqdvwbXnG3uPBQVpJHNMz+lYpSn9K8KTq7tyBY=,tag:ccFS4gNRGpkTU89+jtayEQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:9bVY3KTq82lai95sKjrxCsstGpoxKidv/oIEEpBk0g3jSzT1r08pZpT+ShctTJAH80K0mWrBH8TwMaAd7KH37NTN2zPpyJlHSYwwMPUsQgHZAvXCpkT0rJYY6FYYDPD2cWAxy7zM6hHoJXtk+FEWn2ofTc6ufhau9DQJpwOgLxI2vJaJiMJ2QVdyE4jvhaRI6pTorV+Ba8qFspc/Rzrofl6Go0ZN1IWjWJ1N1DREkycmyxk3,iv:KSunYh+iJK9WtDa2Nlb6082/lFIRkpdgVitCiCugi+I=,tag:aMdN3L+ri/WXZVZAEN2hyg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:rLOOkMN4cr2NdboGj1zOQVylB8gUKERWGNZVbo0+YEmjEm1TS0tfWliu0ciV6Qo3VuLiDQYaP3K5ffyUAqQkAXgCxwnqfOHHipDleMw20QK+GP7plwNDFw==,iv:CIf9nlW9BvkjyXQ86tO4HcrOEr6FhBeE9TCTYjR9swA=,tag:wNjSqPbB38LM+QHawM/Y9A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:QxJoFQTI30N/uOAYfST0kQ==,iv:sgKKN+gC8KeCQ5Dm3n9TEmwpIlraOUkS/DV7WNELNJM=,tag:2RpTTDYmWRNZRpOLJmTpaw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2P8/SakDosjQ1jgYkT/PzHiH0TSAMpVYwsDpXD8j7w5q4pg1swZAu2qOinX10jYrJg5OkpmsEOn+/hS380k3OvND2tF4MxBOgsr2At/yIMnYiDsg4NAd+w==,iv:i+mSgg/O1635+b1XicE86157X39oKLEn9PTy6Fb0BKM=,tag:KcCWLeSh1LCG+FOo7cTDzQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:7KWkESibgWSviem8QoacPw==,iv:yMroNgSarmFykqdE1w7LRcFHgzWvIgmXFRlzYaHtB8s=,tag:QhNwW/lSXLsFMh2i833RBw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:pTCvhd3iofbp9BdacLct5mHy9+zPf2x4GsbCiGmfSuWB5DSlwgr6wm4+xkpXT1T7Zbl7/2JbXacLXB0VH86D7K5DMZLpeYB1RHK0wdN6TflobQS9cxx+Ow==,iv:O5GxOr26gZnJ6PIHuKD+/SsL7IYHH4q6QHaycG3lHEQ=,tag:zgzFPk/2e4rfuZwDAH7OPQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghostfolio-env
sops:
    age:
        - recipient: age1e8k7asxtckf8nmxnf8lvlp4dzcgsnaamdj6q9pl9e2w3mhhz69ts3pyhuz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNGovbHgyZGNkOE5ESTdw
            dHV5b1VZSG9FaFlIK1ZUeUFjbVE3cGJYSjFVCnh2cEtTbGVCb0g5VUNsTml3TXl5
            bEtCVTFuL3ZMMlhZOVFiWkt0bDFoMlkKLS0tIEJuL2NpL213V2hZMS94SE5ZcWs1
            a25sa0pNa0VWZmo3ajJGdUR5amRrUFEKI5Kw7k5xYgiq8pdSGYhMXOjCawM4VPrP
            ONpD0QqE/Sohe8j3pbtBn6ByxQRSOQ9LFXBe0DkiXncPJYb5t5lb9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T13:29:13Z"
    mac: ENC[AES256_GCM,data:Iu8b6cinDg9vZ7Nbu76j01l6Jm84+Rps4oLGFJpBEcoicMidzJmJEtAIaLpzlFYEFwXX2Mwg5V9jq4gE5KdMv8LH+2xgfc6CIOFW1sHp21lDJBgroc4CtKR7DXlZVwpGS+JGehzYNWa6v8StKdd8Fw0c+rqetmItbZZtZkuHxJ4=,iv:0cWlSdK+wiFpBZwDsGqxOPqu9CppJ2MWiuk3Kc66rtA=,tag:tN6NLl43d5gAwegx8iz1Cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
