apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf

  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
     # securityContext:
     #   fsGroup: 1000 # www-data group ID
     #   runAsUser: 1000 # www-data user ID
     #   runAsGroup: 1000 # www-data group ID

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.25.0
          


          envFrom:
          - configMapRef:
              name: audiobookshelf-configmap
         # - secretRef:
         #     name: audiobookshelf-container-env



          ports:
            - containerPort: 3005
              protocol: tcp
#
#          securityContext:
#            allowPrivilegeEscalation: false
#
#          volumeMounts:
#            - name: audiobookshelf-audiobooks
#              mountPath: /etc/audiobookshelf/audiobooks
#             - name: audiobookshelf-podcasts
#              mountPath: /etc/audiobookshelf/podcasts
#            - name: audiobookshelf-config
#              mountPath: /etc/audiobookshelf/config
#             - name: audiobookshelf-metadata
#              mountPath: /etc/audiobookshelf/metadata
#
#      volumes:
#        - name: audiobookshelf-audiobooks
#          persistentVolumeClaim:
#            claimName: audiobookshelf-audiobooks-pvc
#        - name: audiobookshelf-podcasts
#          persistentVolumeClaim:
#            claimName: audiobookshelf-podcasts-pvc
#        - name: audiobookshelf-config
#          persistentVolumeClaim:
#            claimName: audiobookshelf-config-pvc
#        - name: audiobookshelf-metadata
#          persistentVolumeClaim:
#            claimName: audiobookshelf-metadata-pvc
